export const modesTypes = {
  ADD: "ADD",
  NOT_DONE: "NOT_DONE",
  EDIT: "EDIT",
  CHANGE_MODE: "CHANGE_MODE",
};
export const todosTypes = {
  ADD_TODO: "ADD_TODO",
  EDIT_TODO: "EDIT_TODO",
  SET_ACTIVE_TODO: "SET_ACTIVE_TODO",
  EDIT_COMPLETION: "EDIT_COMPLETION",
  DELETE_TODO: "DELETE_TODO",
};
